#include<iostream>
#include<string>

using namespace std;
int main(){
    int marks = 71;
    // if statement

//    if (marks > 90){
//    	cout<<"A grade";
//        
//		}	
//		
//	if (marks > 90){
//    	cout<<"A grade";
//		}
//	else {
//		cout<<"Fail";
//	}

       // Nested if statement

//        int x = 6; 
//        if (x%2 == 0){
//            if (x%3 == 0){
//                cout<<"Number is divisible by 2 and 3";
//
//            }
//        }



//        if (marks  > 90){
//            cout<<"A1 Grade";
//        }
//        else if (marks > 80){
//            cout<<"B Grade";
//        }
//        else if (marks > 70){
//            cout<<"C Grade";
//
//        }
//        else if (marks > 60){
//            cout<<"D Grade";
//
//        }
//         else{
//            cout<<"Fail";    
//
//         }


        int n  = 12 ;
        switch(n){
            case 1:
                cout<<"One value of n";
            break;

            case 2:
            cout<<"Two value of n";
            break;

            case 4:
            cout<<"Jafri value of n";
            break;
        
            default:
                cout<<"Not matching....";
                break;

        }


}
